### PR TITLE
[TAS-86] Count up timer to keep track of time

### PR DESCRIPTION
**Pull request by algebra2boy**
**PR Requirements** (checkmark the following todo if applies)
- [ ] Tests were written to verify its correctness
- [ ] Document any code on Notion that requires documentation
- [x] Run linting and prettier using `npm run lint && npm run format`
- [x] Include picture(s) for any UI change (frontend only)

**PR Description**
This PR adds a simple count-up timer button to the header options menu. This allows students to track how much time they spend working on a single question. When a student clicks the button, it will start the timer and count upward. When the timer is counting and a student clicks again, it will stop the timer (this is useful when a student wants to stop working on a question when they want to take a break and continue working on their previous progress). When a student clicks again, it will return to the timer showing the time and continue the time tracking. Another feature is when a student double clicks on the timer button, it will reset back to 0:00, in case if they want to time themselves again. 

The branch name should've been "frontend/count-up"

https://github.com/cics-web-dev/Chem-Web-App/assets/103079472/0ebc8493-9cbe-4a92-91e7-8ffebcd0c2d7

### CODE REVIEW

**Review by shamanth-kuthpadi — APPROVED** [review]
Good Work!

**Comment by DarzyD** [comment]
Looks good to me!

**Review by DarzyD — APPROVED** [review]

**Review by weebao — COMMENTED** [review]
The Clock and Clock Pause icons are a bit confusing and hard to see so I would recommend using Player-Play and Player-Pause icons of Tabler

**Comment by algebra2boy** [comment]
> The Clock and Clock Pause icons are a bit confusing and hard to see so I would recommend using Player-Play and Player-Pause icons of Tabler

Great suggestion! I have gone ahead and changed my icon to Player-Play and Player-Pause icons.

**Pull request merged**
